# Generated by Django 2.2.11 on 2020-04-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0002_auto_20200411_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
    ]
