# Generated by Django 2.2.11 on 2020-04-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='dt_cricao',
            new_name='dt_criacao',
        ),
    ]
