# Generated by Django 2.2.11 on 2020-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=30)),
                ('email', models.EmailField(max_length=240)),
                ('ocupacao', models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor'), ('Pesquisador', 'Pesquisador')], max_length=50)),
                ('resumo_perfil', models.TextField()),
            ],
        ),
    ]
