# Generated by Django 2.2.11 on 2020-04-08 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('conteudo', models.TextField()),
                ('dt_cricao', models.DateTimeField(auto_now_add=True)),
                ('dt_publicacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Publicado', 'Publicado')], max_length=15)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autor.Autor')),
            ],
        ),
    ]
