# Generated by Django 2.2.11 on 2020-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome Completo')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('formacao', models.CharField(choices=[('Ens. Médio', 'Ens. Médio'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo')], max_length=30, verbose_name='Formação')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Curriculos',
            },
        ),
    ]
